// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTnV7Ny0fHdsJ6a8uyKoAdlSjy8sppyU',
    appId: '1:909755155985:web:785c53c6c21a3e224b13b0',
    messagingSenderId: '909755155985',
    projectId: 'hacer-serbest-243301005',
    authDomain: 'hacer-serbest-243301005.firebaseapp.com',
    storageBucket: 'hacer-serbest-243301005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-yddw7td4Ph1bA3LN5j34pOAKaymt84',
    appId: '1:909755155985:android:970a70971ed28c474b13b0',
    messagingSenderId: '909755155985',
    projectId: 'hacer-serbest-243301005',
    storageBucket: 'hacer-serbest-243301005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmcv96rHfJafAxYzCVl0hz9hZgJTCX_o',
    appId: '1:909755155985:ios:8c0600789dedc3254b13b0',
    messagingSenderId: '909755155985',
    projectId: 'hacer-serbest-243301005',
    storageBucket: 'hacer-serbest-243301005.firebasestorage.app',
    iosBundleId: 'com.example.ogrencinoHacerserbestFlutterProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmcv96rHfJafAxYzCVl0hz9hZgJTCX_o',
    appId: '1:909755155985:ios:8c0600789dedc3254b13b0',
    messagingSenderId: '909755155985',
    projectId: 'hacer-serbest-243301005',
    storageBucket: 'hacer-serbest-243301005.firebasestorage.app',
    iosBundleId: 'com.example.ogrencinoHacerserbestFlutterProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTnV7Ny0fHdsJ6a8uyKoAdlSjy8sppyU',
    appId: '1:909755155985:web:c23b87ac02768d0d4b13b0',
    messagingSenderId: '909755155985',
    projectId: 'hacer-serbest-243301005',
    authDomain: 'hacer-serbest-243301005.firebaseapp.com',
    storageBucket: 'hacer-serbest-243301005.firebasestorage.app',
  );
}
